app = "campus-market"
primary_region = "cdg"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8080
min_machines_running = 0

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
